#!/usr/bin/env python
# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
# All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate the minimal TFM API bindings used by the client.

This is intentionally small and first-party. It reads the canonical OpenAPI
spec and emits endpoint and enum metadata needed by the client without depending on
an external OpenAPI client generator.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import hashlib
import keyword
import os
import re
import sys
import urllib.request
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - exercised only in bare dev envs.
    yaml = None

DEFAULT_OUTPUT = Path('kumo_relational_engine/client/generated/tfm_api.py')
DEFAULT_STRIP_PREFIX = ''

_LINE_LENGTH = 80

HTTP_METHODS = {
    'delete',
    'get',
    'patch',
    'post',
    'put',
}


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Generate client TFM API metadata from an OpenAPI spec.'
    )
    parser.add_argument(
        '--spec',
        required=True,
        help='Local path or URL to the canonical OpenAPI YAML/JSON spec.',
    )
    parser.add_argument(
        '--output',
        default=str(DEFAULT_OUTPUT),
        help=f'Generated Python output path. Defaults to {DEFAULT_OUTPUT}.',
    )
    parser.add_argument(
        '--strip-prefix',
        default=DEFAULT_STRIP_PREFIX,
        help='Optional path prefix to strip from generated endpoint paths.',
    )
    parser.add_argument(
        '--check',
        action='store_true',
        help='Exit non-zero if output is not up to date.',
    )
    parser.add_argument(
        '--validate-contract',
        action='store_true',
        help='Validate generated response models and constants against spec.',
    )
    args = parser.parse_args()

    output = Path(args.output)
    spec_text = _read_source(args.spec)
    spec = _load_spec(spec_text, args.spec)
    code = generate_code(
        spec,
        spec_text=spec_text,
        source=args.spec,
        strip_prefix=args.strip_prefix,
        output_path=output,
    )

    if args.validate_contract:
        errors = validate_generated_code(spec, code)
        if errors:
            print('\n\n'.join(errors), file=sys.stderr)
            return 1
        if not args.check:
            return 0

    if args.check:
        actual = output.read_text() if output.exists() else ''
        if actual != code:
            print(f'{output} is not up to date', file=sys.stderr)
            return 1
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(code)
    _write_provenance(output, code, args.spec)
    return 0


def generate_code_from_source(
    source: str,
    *,
    strip_prefix: str = DEFAULT_STRIP_PREFIX,
    output_path: Path = DEFAULT_OUTPUT,
) -> str:
    spec_text = _read_source(source)
    spec = _load_spec(spec_text, source)
    return generate_code(
        spec,
        spec_text=spec_text,
        source=source,
        strip_prefix=strip_prefix,
        output_path=output_path,
    )


def generate_code(
    spec: dict[str, Any],
    *,
    spec_text: str,
    source: str,
    strip_prefix: str = DEFAULT_STRIP_PREFIX,
    output_path: Path = DEFAULT_OUTPUT,
) -> str:
    operations = _extract_operations(spec, strip_prefix=strip_prefix)
    constants = _extract_constants(spec)
    schemas = spec.get('components', {}).get('schemas', {})
    schema_names = tuple(sorted(schemas))
    response_model_names = _generated_response_model_names(schemas)
    spec_hash = hashlib.sha256(spec_text.encode()).hexdigest()
    source_label = _stable_source_label(source)

    lines = [
        '# Code generated by scripts/generate_tfm_api.py; DO NOT EDIT.',
        f'# Source: {source_label}',
        f'# Source SHA256: {spec_hash}',
        '',
        'from collections.abc import Mapping',
        'from dataclasses import dataclass',
        'from typing import Any, Final',
        '',
        'from kumo_relational_engine.client.endpoints import Endpoint, HTTPMethod',
        '',
        '',
        '@dataclass(frozen=True)',
        'class TFMOperation:',
        '    operation_id: str',
        '    endpoint: Endpoint',
        '    request_schema: str | None = None',
        '    response_schema: str | None = None',
        '    summary: str | None = None',
        '',
        '',
    ]

    lines.extend(_constant_lines(constants))
    lines.extend(_response_model_lines(schemas))
    lines.extend(_tuple_constant_lines('TFM_SCHEMA_NAMES', schema_names))
    lines.extend(['', '', 'class TFMOperations:'])
    if operations:
        for operation in operations:
            lines.extend(_operation_lines(operation))
    else:
        lines.append('    pass')

    lines.extend(
        [
            '',
            'TFM_ENDPOINTS_BY_OPERATION_ID: Final[dict[str, Endpoint]] = {',
        ]
    )
    for operation in operations:
        attr = operation['attr_name']
        operation_id = operation['operation_id']
        lines.append(f'    {operation_id!r}: TFMOperations.{attr}.endpoint,')
    lines.extend(
        [
            '}',
            '',
            '',
            '__all__ = [',
        ]
    )
    exported = [
        'TFMOperation',
        'TFMOperations',
        'TFM_ENDPOINTS_BY_OPERATION_ID',
        'TFM_SCHEMA_NAMES',
        *response_model_names,
        *constants,
    ]
    lines.extend(f'    {name!r},' for name in _sorted_dunder_all(exported))
    lines.extend(
        [
            ']',
            '',
        ]
    )
    code = '\n'.join(lines)
    _assert_importable_syntax(code, output_path)
    return code


def validate_generated_code(spec: dict[str, Any], code: str) -> list[str]:
    errors: list[str] = []
    schemas = spec.get('components', {}).get('schemas', {})

    for schema_name in ('PredictionItem', 'PredictionResponse'):
        schema = schemas.get(schema_name)
        if not isinstance(schema, dict):
            errors.append(f'Missing schema: {schema_name}')
            continue

        expected_fields = tuple(schema.get('properties', {}))
        actual_fields = _generated_dataclass_fields(code, schema_name)
        if actual_fields != expected_fields:
            errors.append(
                _format_sequence_diff(
                    f'{schema_name} fields differ from spec properties',
                    expected_fields=expected_fields,
                    actual_fields=actual_fields,
                )
            )

        missing_required = tuple(
            field
            for field in schema.get('required', [])
            if field not in actual_fields
        )
        if missing_required:
            errors.append(
                f'{schema_name} is missing required spec fields: '
                f'{", ".join(missing_required)}'
            )

    expected_output_fields = tuple(
        _nested_enum_at(schemas.get('OutputSpec', {}), ('fields', 'items'))
    )
    actual_output_fields = _generated_constant_tuple(
        code,
        'TFM_OUTPUT_FIELD_VALUES',
    )
    if actual_output_fields != expected_output_fields:
        errors.append(
            _format_sequence_diff(
                'TFM_OUTPUT_FIELD_VALUES differs from OutputSpec.fields enum',
                expected_fields=expected_output_fields,
                actual_fields=actual_output_fields,
            )
        )

    prediction_operations = _operations_by_request_schema(
        spec, 'PredictionRequest'
    )
    if not prediction_operations:
        errors.append(
            'Missing operation with request schema: PredictionRequest'
        )
    for operation_id, operation in prediction_operations:
        response_schema = _success_response_schema(operation)
        if response_schema != 'PredictionResponse':
            errors.append(
                f'{operation_id} success response schema must be '
                f"'PredictionResponse', got {response_schema!r}"
            )

    return errors


def _read_source(source: str) -> str:
    if _looks_like_url(source):
        url = _normalize_spec_url(source)
        request = urllib.request.Request(url)
        token = os.environ.get('GITLAB_TOKEN') or os.environ.get(
            'PRIVATE_TOKEN'
        )
        if token:
            request.add_header('PRIVATE-TOKEN', token)
        with urllib.request.urlopen(request) as response:
            return response.read().decode()
    return Path(source).read_text()


def _stable_source_label(source: str) -> str:
    if _looks_like_url(source):
        return _normalize_spec_url(source)

    source_path = Path(source).resolve()
    for parent in source_path.parents:
        if (parent / '.git').exists():
            return source_path.relative_to(parent).as_posix()
    return source_path.name


def _load_spec(spec_text: str, source: str) -> dict[str, Any]:
    if source.endswith('.json'):
        import json

        spec = json.loads(spec_text)
    else:
        if yaml is None:
            raise RuntimeError(
                'PyYAML is required to generate TFM API metadata from YAML. '
                "Install this repo with the 'codegen' extra."
            )
        spec = yaml.safe_load(spec_text)
    if not isinstance(spec, dict):
        raise ValueError('OpenAPI spec must parse to an object.')
    if 'openapi' not in spec or 'paths' not in spec:
        raise ValueError('OpenAPI spec must contain openapi and paths fields.')
    return spec


def _extract_operations(
    spec: dict[str, Any],
    *,
    strip_prefix: str,
) -> list[dict[str, str | None]]:
    operations: list[dict[str, str | None]] = []
    paths = spec.get('paths', {})
    for path in sorted(paths):
        path_item = paths[path] or {}
        for method in sorted(path_item):
            if method.lower() not in HTTP_METHODS:
                continue
            operation = path_item[method] or {}
            operation_id = operation.get('operationId')
            if not operation_id:
                operation_id = _fallback_operation_id(method, path)
            operations.append(
                {
                    'attr_name': _snake_case(operation_id),
                    'operation_id': operation_id,
                    'path': _strip_path_prefix(path, strip_prefix),
                    'method': method.upper(),
                    'request_schema': _request_schema(operation),
                    'response_schema': _success_response_schema(operation),
                    'summary': operation.get('summary'),
                }
            )
    return operations


def _extract_constants(
    spec: dict[str, Any],
) -> dict[str, str | tuple[str, ...]]:
    schemas = spec.get('components', {}).get('schemas', {})
    prediction_request = schemas.get('PredictionRequest', {})
    output_spec = schemas.get('OutputSpec', {})
    task_spec = schemas.get('TaskSpec', {})

    version_values = _enum_at(prediction_request, 'version')
    model_values = _enum_at(prediction_request, 'model')
    output_fields = _nested_enum_at(output_spec, ('fields', 'items'))
    task_kinds = _enum_at(task_spec, 'kind')

    constants: dict[str, str | tuple[str, ...]] = {}
    if version_values:
        constants['TFM_API_VERSION'] = version_values[0]
        constants['TFM_API_VERSION_VALUES'] = tuple(version_values)
    if model_values:
        constants['TFM_MODEL_VALUES'] = tuple(model_values)
        for value in model_values:
            constants[f'TFM_MODEL_{_constant_token(value)}'] = value
    if output_fields:
        constants['TFM_OUTPUT_FIELD_VALUES'] = tuple(output_fields)
        for value in output_fields:
            constants[f'TFM_OUTPUT_FIELD_{_constant_token(value)}'] = value
    if task_kinds:
        constants['TFM_TASK_KIND_VALUES'] = tuple(task_kinds)
        for value in task_kinds:
            constants[f'TFM_TASK_KIND_{_constant_token(value)}'] = value
    return constants


def _constant_lines(
    constants: dict[str, str | tuple[str, ...]],
) -> list[str]:
    lines: list[str] = []
    for name in sorted(constants):
        value = constants[name]
        if isinstance(value, tuple):
            lines.extend(_tuple_constant_lines(name, value))
        else:
            declaration = f'{name}: Final[str] = {value!r}'
            if len(declaration) > _LINE_LENGTH:
                # Match what the formatter would do, so generated output needs
                # no formatting pass and stays byte-comparable to the checkout.
                lines.extend(
                    [
                        f'{name}: Final[str] = (',
                        f'    {value!r}',
                        ')',
                    ]
                )
            else:
                lines.append(declaration)
    lines.extend(['', ''])
    return lines


def _write_provenance(output: Path, code: str, spec_source: str) -> None:
    r"""Record what was generated, beside the generated file.

    The drift tests need a checkout of the contract, which most environments do
    not have. This record lets those environments still detect the failure that
    does not need it: the generated file edited by hand rather than
    regenerated. It moves with the file precisely because it is written here.
    """
    import json

    stamped = re.search(r'# Source SHA256: ([0-9a-f]{64})', code)
    record = {
        'generated_file': output.name,
        'generated_sha256': hashlib.sha256(code.encode()).hexdigest(),
        'generator': 'scripts/generate_tfm_api.py',
        'source_path': Path(spec_source).name,
        'source_repository': 'structured-data-api',
        'source_revision': _spec_revision(spec_source),
        'source_sha256': stamped.group(1) if stamped else '',
    }
    (output.parent / 'PROVENANCE.json').write_text(
        json.dumps(record, indent=2, sort_keys=True) + '\n'
    )


def _spec_revision(spec_source: str) -> str:
    r"""The contract's git revision, when the spec came from a checkout."""
    import subprocess

    path = Path(spec_source)
    if not path.exists():
        return ''
    try:
        return subprocess.check_output(
            ['git', '-C', str(path.parent), 'rev-parse', 'HEAD'],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (subprocess.CalledProcessError, OSError):
        return ''


def _sorted_dunder_all(names: list[str]) -> list[str]:
    r"""Order ``__all__`` the way ruff's RUF022 expects, so generated output is
    lint-clean and the byte-for-byte drift test stays enforceable.

    Constant-cased names sort ahead of class-cased ones, each alphabetically.
    """

    def key(name: str) -> tuple[int, str]:
        return (0 if name.replace('_', '').isupper() else 1, name)

    return sorted(names, key=key)


def _generated_response_model_names(schemas: dict[str, Any]) -> tuple[str, ...]:
    names = []
    if 'PredictionItem' in schemas:
        names.append('PredictionItem')
    if 'PredictionResponse' in schemas:
        names.append('PredictionResponse')
    return tuple(names)


def _response_model_lines(schemas: dict[str, Any]) -> list[str]:
    if not {'PredictionItem', 'PredictionResponse'} <= set(schemas):
        return []
    return [
        '@dataclass(frozen=True)',
        'class PredictionItem:',
        '    id: str | None = None',
        '    row_index: int | None = None',
        '    forecast_step: int | None = None',
        '    prediction: Any | None = None',
        '    probabilities: dict[str, float] | None = None',
        '    scores: tuple[float, ...] | None = None',
        '    rankings: tuple[dict[str, Any], ...] | None = None',
        '    embeddings: tuple[float, ...] | None = None',
        '    quantiles: dict[str, float] | None = None',
        '    explanation: dict[str, Any] | None = None',
        '    metadata: dict[str, Any] | None = None',
        '',
        '    @classmethod',
        "    def from_dict(cls, data: Mapping[str, Any]) -> 'PredictionItem':",
        '        return cls(',
        "            id=str(data['id']) if 'id' in data else None,",
        "            row_index=_int_or_none(data.get('row_index')),",
        "            forecast_step=_int_or_none(data.get('forecast_step')),",
        "            prediction=data.get('prediction'),",
        "            probabilities=_float_dict(data.get('probabilities')),",
        "            scores=_float_tuple(data.get('scores')),",
        "            rankings=_mapping_tuple(data.get('rankings')),",
        "            embeddings=_float_tuple(data.get('embeddings')),",
        "            quantiles=_float_dict(data.get('quantiles')),",
        "            explanation=_dict_or_none(data.get('explanation')),",
        "            metadata=_dict_or_none(data.get('metadata')),",
        '        )',
        '',
        '',
        '@dataclass(frozen=True)',
        'class PredictionResponse:',
        '    id: str',
        '    model: str',
        '    predictions: tuple[PredictionItem, ...]',
        '    metadata: dict[str, Any]',
        '',
        '    @classmethod',
        "    def from_dict(cls, data: Mapping[str, Any]) -> 'PredictionResponse':",
        '        return cls(',
        "            id=str(data['id']),",
        "            model=str(data['model']),",
        '            predictions=tuple(',
        '                PredictionItem.from_dict(item)',
        "                for item in data.get('predictions', [])",
        '            ),',
        "            metadata=dict(data.get('metadata', {})),",
        '        )',
        '',
        '',
        'def _float_dict(value: Any) -> dict[str, float] | None:',
        '    if value is None:',
        '        return None',
        '    if not isinstance(value, Mapping):',
        "        raise TypeError('Expected mapping value')",
        '    return {str(key): float(val) for key, val in value.items()}',
        '',
        '',
        'def _int_or_none(value: Any) -> int | None:',
        '    if value is None:',
        '        return None',
        '    return int(value)',
        '',
        '',
        'def _float_tuple(value: Any) -> tuple[float, ...] | None:',
        '    if value is None:',
        '        return None',
        '    return tuple(float(item) for item in value)',
        '',
        '',
        'def _mapping_tuple(value: Any) -> tuple[dict[str, Any], ...] | None:',
        '    if value is None:',
        '        return None',
        '    return tuple(dict(item) for item in value)',
        '',
        '',
        'def _dict_or_none(value: Any) -> dict[str, Any] | None:',
        '    if value is None:',
        '        return None',
        '    return dict(value)',
        '',
        '',
    ]


def _tuple_constant_lines(name: str, values: tuple[str, ...]) -> list[str]:
    lines = [f'{name}: Final[tuple[str, ...]] = (']
    lines.extend(f'    {value!r},' for value in values)
    lines.append(')')
    return lines


def _operation_lines(operation: dict[str, str | None]) -> list[str]:
    attr_name = operation['attr_name']
    if not isinstance(attr_name, str):
        raise TypeError('operation attr_name must be a string')
    return [
        f'    {attr_name}: Final[TFMOperation] = TFMOperation(',
        f'        operation_id={operation["operation_id"]!r},',
        '        endpoint=Endpoint(',
        f'            path={operation["path"]!r},',
        f'            method=HTTPMethod.{operation["method"]},',
        '        ),',
        f'        request_schema={operation["request_schema"]!r},',
        f'        response_schema={operation["response_schema"]!r},',
        f'        summary={operation["summary"]!r},',
        '    )',
        '',
    ]


def _request_schema(operation: dict[str, Any]) -> str | None:
    content = operation.get('requestBody', {}).get('content', {})
    schema = content.get('application/json', {}).get('schema')
    return _schema_ref_name(schema)


def _success_response_schema(operation: dict[str, Any]) -> str | None:
    responses = operation.get('responses', {})
    for status in ('200', '201', '202', 'default'):
        response = responses.get(status)
        if not response:
            continue
        content = response.get('content', {})
        schema = content.get('application/json', {}).get('schema')
        name = _schema_ref_name(schema)
        if name is not None:
            return name
    return None


def _schema_ref_name(schema: dict[str, Any] | None) -> str | None:
    if not schema:
        return None
    ref = schema.get('$ref')
    if not isinstance(ref, str):
        return None
    prefix = '#/components/schemas/'
    if not ref.startswith(prefix):
        raise ValueError(f'Unsupported schema reference: {ref}')
    return ref[len(prefix) :]


def _operations_by_request_schema(
    spec: dict[str, Any],
    schema_name: str,
) -> list[tuple[str, dict[str, Any]]]:
    operations: list[tuple[str, dict[str, Any]]] = []
    for path_item in spec.get('paths', {}).values():
        if not isinstance(path_item, dict):
            continue
        for method, operation in path_item.items():
            if method.lower() not in HTTP_METHODS:
                continue
            if not isinstance(operation, dict):
                continue
            if _request_schema(operation) != schema_name:
                continue
            operation_id = operation.get('operationId')
            if isinstance(operation_id, str):
                operations.append((operation_id, operation))
    return operations


def _enum_at(schema: dict[str, Any], property_name: str) -> list[str]:
    prop = schema.get('properties', {}).get(property_name, {})
    values = prop.get('enum', [])
    return [str(value) for value in values]


def _nested_enum_at(
    schema: dict[str, Any],
    path: tuple[str, ...],
) -> list[str]:
    current: Any = schema.get('properties', {})
    for key in path:
        if not isinstance(current, dict):
            return []
        current = current.get(key, {})
    values = current.get('enum', []) if isinstance(current, dict) else []
    return [str(value) for value in values]


def _strip_path_prefix(path: str, prefix: str) -> str:
    if not prefix:
        return path
    if path == prefix:
        return '/'
    if path.startswith(prefix + '/'):
        return path[len(prefix) :]
    return path


def _fallback_operation_id(method: str, path: str) -> str:
    tokens = re.findall(r'[A-Za-z0-9]+', path)
    return '_'.join([method.lower(), *tokens])


def _snake_case(value: str) -> str:
    value = re.sub(r'(.)([A-Z][a-z]+)', r'\1_\2', value)
    value = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', value)
    value = re.sub(r'[^0-9A-Za-z_]+', '_', value).lower().strip('_')
    if not value:
        value = 'operation'
    if value[0].isdigit():
        value = f'operation_{value}'
    if keyword.iskeyword(value):
        value = f'{value}_'
    return value


def _constant_token(value: str) -> str:
    token = re.sub(r'[^0-9A-Za-z]+', '_', value).strip('_').upper()
    if not token:
        token = 'VALUE'
    if token[0].isdigit():
        token = f'VALUE_{token}'
    return token


def _looks_like_url(source: str) -> bool:
    return source.startswith('http://') or source.startswith('https://')


def _normalize_spec_url(source: str) -> str:
    if '/-/blob/' in source:
        return source.replace('/-/blob/', '/-/raw/', 1)
    return source


def _generated_dataclass_fields(code: str, class_name: str) -> tuple[str, ...]:
    module = ast.parse(code)
    for node in module.body:
        if isinstance(node, ast.ClassDef) and node.name == class_name:
            fields: list[str] = []
            for item in node.body:
                if isinstance(item, ast.AnnAssign):
                    target = item.target
                    if isinstance(target, ast.Name):
                        fields.append(target.id)
            return tuple(fields)
    return ()


def _generated_constant_tuple(code: str, name: str) -> tuple[str, ...]:
    module = ast.parse(code)
    for node in module.body:
        if not isinstance(node, ast.AnnAssign):
            continue
        target = node.target
        if not isinstance(target, ast.Name) or target.id != name:
            continue
        value = ast.literal_eval(node.value)
        if not isinstance(value, tuple):
            raise ValueError(f'{name} must be generated as a tuple')
        return tuple(str(item) for item in value)
    return ()


def _format_sequence_diff(
    title: str,
    *,
    expected_fields: tuple[str, ...],
    actual_fields: tuple[str, ...],
) -> str:
    diff = '\n'.join(
        difflib.unified_diff(
            [f'{field}\n' for field in actual_fields],
            [f'{field}\n' for field in expected_fields],
            fromfile='generated',
            tofile='spec',
            lineterm='',
        )
    )
    return f'{title}:\n{diff}'


def _assert_importable_syntax(code: str, output_path: Path) -> None:
    compile(code, str(output_path), 'exec')


if __name__ == '__main__':
    raise SystemExit(main())
