// SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES.
// All rights reserved.
// SPDX-License-Identifier: Apache-2.0

#include <pybind11/pybind11.h>
#include <pybind11/numpy.h>
#include <pybind11/stl.h>
#include <string>
#include <tuple>
#include <algorithm>
#include <iostream>
#include <unordered_map>
#include <random>

#define PHMAP_HASH_ROTL32(x, r) (x << r) | (x >> (32 - r))

namespace py = pybind11;

namespace relationallib{
typedef std::string node_type;
typedef std::string rel_type;
typedef std::tuple<std::string, std::string, std::string> edge_type;

inline rel_type to_rel_type(const edge_type& key) {
  return std::get<0>(key) + "__" + std::get<1>(key) + "__" + std::get<2>(key);
}
using pair_int64_t = std::pair<int64_t, int64_t>;

// A hash function used to hash a pair
struct hash_pair {
  template <class T1, class T2>
  size_t operator()(const std::pair<T1, T2>& p) const
  {
    // taken from boost
    const int64_t hash_const = 0xd989bcacc137dcd5ull;
    int64_t hash1 = std::hash<T1>{}(p.first) * hash_const >> 32u;
    int64_t hash2 = std::hash<T2>{}(p.second) * hash_const >> 32u;

    const uint32_t c1 = 0xcc9e2d51;
    const uint32_t c2 = 0x1b873593;

    hash1 *= c1;
    hash1 = PHMAP_HASH_ROTL32(hash1,15);
    hash1 *= c2;

    hash2 ^= hash1;
    hash2 = PHMAP_HASH_ROTL32(hash2,13);
    hash2 = hash2*5+0xe6546b64;
    return hash2;
  }
};

class Mapper {
  // A simplified implementation of pyg_lib/csrc/sampler/cpu/mapper.h
 public:
  std::pair<int64_t, bool> insert(const pair_int64_t& node) {
    std::pair<int64_t, bool> res;
    auto out = to_local_map.insert({node, curr});
    res = std::pair<int64_t, bool>(out.first->second, out.second);
    if (res.second)
      ++curr;
    return res;
  }

 private:
  std::unordered_map<pair_int64_t, int64_t, hash_pair> to_local_map;
  int64_t curr = 0;
};

class IndexTracker {
  // A simplified implementation of pyg_lib/csrc/sampler/cpu/index_tracker.h
  // It keeps track of a set, used for sampling without replacement
 public:
  IndexTracker(const size_t& size) : size_(size) {
    use_vec_ = (size < 100000);

    if (use_vec_)
      vec_.resize(size_, 0);
  }

  bool try_insert(const int64_t& index) {
    if (use_vec_) {
      if (vec_[index] == 0) {
        vec_[index] = 1;
        return true;
      } else
        return false;
    } else
      return set_.insert(index).second;
  }

  void insert(const int64_t& index) {
    if (use_vec_)
      vec_[index] = 1;
    else
      set_.insert(index);
  }

 private:
  const size_t& size_;
  bool use_vec_;
  std::vector<char> vec_;
  std::unordered_set<int64_t> set_;
};

class NeighborSampler {
  public:
  NeighborSampler(
      const std::vector<node_type> node_types,
      const std::vector<edge_type> edge_types,
      const py::dict colptr,
      const py::dict row,
      const py::dict node_time,
      const int seed = 123
  ) : node_types_(node_types), edge_types_(edge_types){
    for (const auto& edge_t: edge_types_)
      rel_types_.push_back(to_rel_type(edge_t));
    validate_arr_dict(colptr, "colptr", rel_types_);
    validate_arr_dict(row, "row", rel_types_);
    has_time_ = (node_time.size() > 0);
    validate_arr_dict(node_time, "node_time", node_types_);
    for (const auto& rel_type: rel_types_){
      colptr_[rel_type] = static_cast<int64_t*>(colptr[py::str(rel_type)].cast<py::array>().request().ptr);
      row_[rel_type] = static_cast<int64_t*>(row[py::str(rel_type)].cast<py::array>().request().ptr);
    }
    for (const auto& node_type: node_types_)
      if (node_time.contains(node_type.c_str()))
        node_time_[node_type] = static_cast<int64_t*>(node_time[py::str(node_type)].cast<py::array>().request().ptr);
    rng_.seed(seed);
    // Possible additional validations:
    //  - ensure that colptr and row sizes are consistent
    //  - ensure that node_time is consistent with colptr, row sizes
    // We skip this for now because the inputs are generated by our
    // code and should be correct.
  }

  void seed(const int seed) {
    rng_.seed(seed);
  }

  void validate_arr_dict(const py::dict& val_dict, std::string dict_name, std::vector<std::string> keys, int dim=1, bool validate_int=true){
    for (const auto& kv : val_dict) {
      std::string node_t = std::string(py::str(kv.first));
      if (std::find(keys.begin(), keys.end(), node_t) == keys.end())
        throw std::runtime_error("Invalid type '" + node_t + "' found in "+dict_name+".");
      py::array arr = kv.second.cast<py::array>();
      validate_arr(arr, "Type '" + node_t + "' in "+dict_name, dim, validate_int);
    }
  }

  void validate_arr(const py::array& val_arr, std::string arr_name, int dim=1, bool validate_int=true){
      if (val_arr.ndim() != dim)
          throw std::runtime_error(arr_name+" is not "+std::to_string(dim)+"D.");
      if (val_arr.size() == 0)
        return;
      if (validate_int && (val_arr.dtype().kind() != 'i' || val_arr.dtype().itemsize() != 8)) {
        throw std::runtime_error(arr_name+" must have dtype int64.");
      }
  }

  void clear_placeholders() {
    num_sampled_nodes_per_hop_.clear();
    num_sampled_edges_per_hop_.clear();
    sampled_cols_.clear();
    sampled_rows_.clear();
    sampled_batch_.clear();
    sampled_node_ids_.clear();
  }

  void init_placeholders() {
  for (const auto& k : node_types_) {
    num_sampled_nodes_per_hop_.insert({k, std::vector<int64_t>(1, 0)});
    sampled_batch_.insert({k, std::vector<int64_t>()});
    sampled_node_ids_.insert({k, std::vector<int64_t>()});
  }
  for (const auto& k : edge_types_) {
    auto k_rel = to_rel_type(k);
    num_sampled_edges_per_hop_.insert({k_rel, std::vector<int64_t>(1, 0)});
    sampled_cols_.insert({k_rel, std::vector<int64_t>()});
    sampled_rows_.insert({k_rel, std::vector<int64_t>()});
  }
}

  void uniform_sample(
      rel_type e_type,
      const pair_int64_t global_src_node,
      const int64_t local_src_node,
      const int64_t count,
      relationallib::Mapper& dst_mapper,
      std::vector<pair_int64_t>& out_global_dst_nodes) {
    if (count == 0)
      return;
    auto colptr_v = colptr_[e_type];
    const auto col_start = colptr_v[std::get<1>(global_src_node)];
    const auto col_end = colptr_v[std::get<1>(global_src_node) + 1];
    if (col_end - col_start == 0)
      return;
    _sample(e_type, global_src_node, local_src_node, col_start, col_end, count,
            dst_mapper, out_global_dst_nodes);
  }

  void node_temporal_sample(
      rel_type e_type,
      const pair_int64_t global_src_node,
      const int64_t local_src_node,
      const int64_t count,
      const int64_t seed_time,
      const int64_t* time,
      relationallib::Mapper& dst_mapper,
      std::vector<pair_int64_t>& out_global_dst_nodes) {
    if (count == 0)
      return;
    auto colptr_v = colptr_[e_type];
    auto col_start = colptr_v[std::get<1>(global_src_node)];
    auto col_end = colptr_v[std::get<1>(global_src_node)+1];
    auto row_v = row_[e_type];
    if (col_end - col_start == 0)
      return;
    // Find new `col_end` such that all neighbors fulfill temporal constraints:
    auto it = std::upper_bound(
        row_v + col_start, row_v + col_end, seed_time,
        [&](const int64_t& a, const int64_t& b) { return a < time[b]; });

    col_end = it - row_v;
    if (col_end - col_start > 1 && time[row_v[col_start]] > time[row_v[col_end - 1]])
      throw std::runtime_error("Found invalid non-sorted temporal neighborhood");

    if (count>0)
      col_start = std::max(col_start, (int64_t)(col_end - count));
    if (col_end - col_start == 0)
      return;

    _sample(e_type, global_src_node, local_src_node, col_start, col_end, count,
            dst_mapper, out_global_dst_nodes);
  }

  void node_temporal_range_sample(
      rel_type e_type,
      const pair_int64_t global_src_node,
      const int64_t local_src_node,
      std::vector<int64_t> time_range,
      const int64_t seed_time,
      const int64_t* time,
      relationallib::Mapper& dst_mapper,
      std::vector<pair_int64_t>& out_global_dst_nodes) {
    auto colptr_v = colptr_[e_type];
    auto col_start = colptr_v[std::get<1>(global_src_node)];
    auto col_end = colptr_v[std::get<1>(global_src_node)+1];
    auto row_v = row_[e_type];
    if (col_end - col_start == 0)
      return;

    int64_t end_time;
    if (time_range.size() > 1){
      int64_t start_time = time_range[0] + seed_time;
      end_time = time_range[1] + seed_time;
      // Find new `col_start` such that all neighbors fulfill temporal constraints:
      auto it = std::upper_bound(
          row_v + col_start, row_v + col_end, start_time,
          [&](const int64_t& a, const int64_t& b) { return a < time[b]; });

      col_start = it - row_v;
    }
    else
      end_time = time_range[0] + seed_time;
    // Find new `col_end` such that all neighbors fulfill temporal constraints:
    auto it = std::upper_bound(
        row_v + col_start, row_v + col_end, end_time,
        [&](const int64_t& a, const int64_t& b) { return a < time[b]; });

    col_end = it - row_v;
    if (col_end - col_start > 1 && time[row_v[col_start]] > time[row_v[col_end - 1]])
      throw std::runtime_error("Found invalid non-sorted temporal neighborhood");

    if (col_end - col_start == 0)
      return;
    _sample(e_type, global_src_node, local_src_node, col_start, col_end, col_end-col_start,
            dst_mapper, out_global_dst_nodes);
  }


  void _sample(
      const rel_type& e_type,
      const pair_int64_t& global_src_node,
      const int64_t& local_src_node,
      const int64_t& col_start,
      const int64_t& col_end,
      const int64_t& count,
      relationallib::Mapper& dst_mapper,
      std::vector<pair_int64_t>& out_global_dst_nodes) {
    const auto population = col_end - col_start;
    // Case 1: Sample the full neighborhood:
    if (count < 0 || count >= population) {
      for (int64_t edge_id = col_start; edge_id < col_end; ++edge_id)
        add_edge(e_type, edge_id, global_src_node, local_src_node, dst_mapper,
                 out_global_dst_nodes);
    }
    // Case 2: Sample without replacement:
    else {
      auto index_tracker = relationallib::IndexTracker(population);
      for (auto i = population - count; i < population; ++i) {
        // rng_.max() is ~ 4B, we can revisit this to sample more
        auto rnd = rng_()%(i+1);
        if (!index_tracker.try_insert(rnd)) {
          rnd = i;
          index_tracker.insert(i);
        }
        const auto edge_id = col_start + rnd;
        add_edge(e_type, edge_id, global_src_node, local_src_node, dst_mapper,
                 out_global_dst_nodes);
      }
    }
  }

  inline void add_edge(
      const rel_type& e_type,
      const int64_t& edge_id,
      const pair_int64_t& global_src_node,
      const int64_t& local_src_node,
      relationallib::Mapper& dst_mapper,
      std::vector<pair_int64_t>& out_global_dst_nodes) {
    const auto global_dst_node_value = row_[e_type][edge_id];
    const auto global_dst_node = std::make_pair(
        std::get<0>(global_src_node), global_dst_node_value);

    const auto res = dst_mapper.insert(global_dst_node);
    if (res.second)  // not yet sampled.
      out_global_dst_nodes.push_back(global_dst_node);
    // handle the global vars below
    num_sampled_edges_per_hop_[e_type]
                              [num_sampled_edges_per_hop_[e_type].size() - 1]++;
    sampled_rows_[e_type].push_back(res.first);
    sampled_cols_[e_type].push_back(local_src_node);
  }

  // row, col, node_id, batch, num_sampled_nodes, num_sampled_edges
  std::tuple<py::dict, py::dict, py::dict, py::dict, py::dict, py::dict>
  sample(
      py::dict num_neighbors,
      py::dict sampling_time_offsets,
      node_type entity_table,
      py::array seed_node,
      py::array seed_time
    ) {
    validate_arr_dict(num_neighbors, "num_neighbors", rel_types_);
    validate_arr_dict(sampling_time_offsets, "sampling_time_offsets", rel_types_, 2, false);
    validate_arr(seed_node, "seed_node");
    validate_arr(seed_time, "seed_time");
    if (std::find(node_types_.begin(), node_types_.end(), entity_table) == node_types_.end())
      throw std::runtime_error("Invalid entity table '"+entity_table+"'.");

    if (has_time_ && seed_time.size() != 0 && seed_time.size() != seed_node.size())
      throw std::runtime_error("'seed_node' and 'seed_time' size mismatch.");

    // each pair is (batch_id, node_id)
    std::unordered_map<node_type, std::vector<pair_int64_t>> sampled_nodes;
    std::unordered_map<node_type, relationallib::Mapper> mapper_dict;
    // Slices corresponding to a type in the buffer row
    std::unordered_map<node_type, std::pair<size_t, size_t>> slice_dict;
    std::vector<int64_t> seed_times;
    init_placeholders();
    for (const auto& k : node_types_) {
      sampled_nodes[k];  // Init an empty vector
      mapper_dict.insert({k, relationallib::Mapper()});
      slice_dict[k] = {0, 0};
    }
    size_t L = 0;  // num_layers
    for (const auto& k : edge_types_) {
      num_sampled_edges_per_hop_.insert(
          {to_rel_type(k), std::vector<int64_t>(1, 0)});
      if (num_neighbors.contains(to_rel_type(k).c_str()) && sampling_time_offsets.contains(to_rel_type(k).c_str()))
        throw std::runtime_error("'sampling_time_offsets' and 'num_neighbors' may not contain the same edge type. '"+to_rel_type(k)+"' appears in both.");
      if (num_neighbors.contains(to_rel_type(k).c_str()))
        L = std::max(L, size_t(num_neighbors[py::str(to_rel_type(k))].cast<py::array>().size()));
      else {
        L = std::max(L, size_t(sampling_time_offsets[py::str(to_rel_type(k))].cast<py::array>().shape(0)));
        if (node_time_.find(std::get<0>(k))== node_time_.end())
          throw std::runtime_error("'sampling_time_offsets' contains '"+to_rel_type(k)+"' but "+std::get<0>(k)+" is not included in 'node_time'.");
        if (sampling_time_offsets[py::str(to_rel_type(k))].cast<py::array>().shape(1) != 2)
          throw std::runtime_error("'sampling_time_offsets' at '"+to_rel_type(k)+"' does not have shape (N, 2).");
      }
    }

    // We fill the buffers with the zero-th layer: seed nodes
    int64_t batch_idx = 0;
    slice_dict[entity_table] = {0, size_t(seed_node.shape(0))};
    const auto seed_data = static_cast<int64_t*>(seed_node.request().ptr);

    // We need to track each batch
    // separately to avoid leakage. Hence we always push pairs
    // <batch_id, node_id>
    auto& curr_sampled_nodes = sampled_nodes[entity_table];
    auto& mapper = mapper_dict[entity_table];
    for (size_t i = 0; i < seed_node.size(); ++i) {
      curr_sampled_nodes.push_back({batch_idx, seed_data[i]});
      mapper.insert({batch_idx, seed_data[i]});
      batch_idx++;
    }
    if (seed_time.size()>0) {
      const auto seed_time_data = static_cast<int64_t*>(seed_time.request().ptr);
      seed_times.reserve(seed_times.size() + seed_node.size());
      for (size_t i = 0; i < seed_node.size(); ++i)
        seed_times.push_back(seed_time_data[i]);
    } else if (node_time_.find(entity_table) != node_time_.end()) {
      // if seed times aren't provided we use node times if available
      const auto node_time_data = node_time_[entity_table];
      seed_times.reserve(seed_times.size() + seed_node.size());
      for (size_t i = 0; i < seed_node.size(); ++i)
        seed_times.push_back(node_time_data[seed_data[i]]);
    }
    num_sampled_nodes_per_hop_[entity_table][0] =
        sampled_nodes[entity_table].size();
    for (auto& node : sampled_nodes[entity_table]) {
      sampled_batch_[entity_table].push_back(std::get<0>(node));
      sampled_node_ids_[entity_table].push_back(std::get<1>(node));
    }
    // The sampling code begins below

    for (size_t ell = 0; ell < L; ++ell) {
      for (const auto& k : edge_types_) {
        // inner loop for edge type k: src->dst
        const auto src = std::get<2>(k);
        const auto dst = std::get<0>(k);
        auto& src_sampled_nodes = sampled_nodes[src];
        auto& dst_mapper = mapper_dict[dst];
        size_t begin, end;
        std::tie(begin, end) = slice_dict.at(src);
        num_sampled_edges_per_hop_[to_rel_type(k)].push_back(0);
        int64_t sample_size=0;
        std::vector<int64_t> time_range;
        if (num_neighbors.contains(to_rel_type(k).c_str())){
          const py::array& num_n_arr = num_neighbors[py::str(to_rel_type(k))].cast<py::array>();
          sample_size = static_cast<int64_t*>(num_n_arr.request().ptr)[ell];
        } else {
          py::object range = sampling_time_offsets[py::str(to_rel_type(k))][py::int_(ell)];
          if (!range[py::int_(0)].is_none())time_range.push_back(range[py::int_(0)].cast<int64_t>());
          time_range.push_back(range[py::int_(1)].cast<int64_t>());
        }
        bool is_static =
            (node_time_.size() == 0 || node_time_.find(dst) == node_time_.end() || seed_times.size() == 0);
        if (is_static){
          for (auto i = begin; i < end; i++) {
            const auto batch_idx = std::get<0>(src_sampled_nodes[i]);
            uniform_sample(
                /*e_type=*/to_rel_type(k),
                /*global_src_node=*/src_sampled_nodes[i],
                /*local_src_node=*/i,
                /*count=*/sample_size,
                /*dst_mapper=*/dst_mapper,
                /*out_global_dst_nodes=*/sampled_nodes[dst]);
          }
        } else {
          const auto dst_time_data = node_time_[dst];
          for (auto i = begin; i < end; i++) {
            const auto batch_idx = std::get<0>(src_sampled_nodes[i]);
            if (time_range.size() > 0)
              node_temporal_range_sample(
                  /*e_type=*/to_rel_type(k),
                  /*global_src_node=*/src_sampled_nodes[i],
                  /*local_src_node=*/i,
                  /*time_range=*/time_range,
                  /*seed_time=*/seed_times[batch_idx],
                  /*time=*/dst_time_data,
                  /*dst_mapper=*/dst_mapper,
                  /*out_global_dst_nodes=*/sampled_nodes[dst]);
            else
              node_temporal_sample(
                  /*e_type=*/to_rel_type(k),
                  /*global_src_node=*/src_sampled_nodes[i],
                  /*local_src_node=*/i,
                  /*count=*/sample_size,
                  /*seed_time=*/seed_times[batch_idx],
                  /*time=*/dst_time_data,
                  /*dst_mapper=*/dst_mapper,
                  /*out_global_dst_nodes=*/sampled_nodes[dst]);
          }
        }
      }
      // Update which slice of the sampled_nodes_dict[k] belongs to which hop
      for (const auto& k : node_types_) {
        slice_dict[k] = {slice_dict.at(k).second, sampled_nodes.at(k).size()};
        num_sampled_nodes_per_hop_.at(k).push_back(slice_dict.at(k).second -
                                                   slice_dict.at(k).first);
        for (int64_t i = slice_dict.at(k).first; i < slice_dict.at(k).second;
             i++) {
          auto node = sampled_nodes.at(k)[i];
          sampled_batch_.at(k).push_back(std::get<0>(node));
          sampled_node_ids_.at(k).push_back(std::get<1>(node));
        }
      }
    }

    // We rewrite std objects into pybind ones for the return value
    py::dict num_sampled_nodes_per_hop_dict;
    py::dict out_node_id;
    py::dict batch;
    for (const auto& k : node_types_) {
      out_node_id[py::str(k)]=py::array_t<int64_t>(sampled_node_ids_[k].size(), sampled_node_ids_[k].data());
      num_sampled_nodes_per_hop_dict[py::str(k)]=py::array_t<int64_t>(
		      num_sampled_nodes_per_hop_[k].size(),
		      num_sampled_nodes_per_hop_[k].data());
      batch[py::str(k)]=py::array_t<int64_t>(sampled_batch_[k].size(), sampled_batch_[k].data());
    }

    py::dict num_sampled_edges_per_hop_dict;
    py::dict out_row;
    py::dict out_col;
    for (const auto& k : edge_types_) {
      auto k_rel = to_rel_type(k);
      // We skip the first edge entry - it's zero
      num_sampled_edges_per_hop_dict[py::str(k_rel)]=py::array_t<int64_t>(
		      num_sampled_edges_per_hop_[k_rel].size() - 1,
		      num_sampled_edges_per_hop_[k_rel].data() + 1);
      const auto row = py::array_t<int64_t>(
		      sampled_rows_[k_rel].size(),
		      sampled_rows_[k_rel].data());
      out_row[py::str(k_rel)] = row;
      const auto col = py::array_t<int64_t>(
		      sampled_cols_[k_rel].size(),
		      sampled_cols_[k_rel].data());
      out_col[py::str(k_rel)] = col;
    }
    clear_placeholders();
    return std::make_tuple(out_row, out_col, out_node_id, batch,
                         num_sampled_nodes_per_hop_dict,
                         num_sampled_edges_per_hop_dict);
  }

  private:
  const std::vector<node_type> node_types_;
  const std::vector<edge_type> edge_types_;
  std::vector<rel_type> rel_types_;
  bool has_time_;
  std::mt19937 rng_;
  std::unordered_map<rel_type, int64_t*> colptr_;
  std::unordered_map<rel_type, int64_t*> row_;
  std::unordered_map<node_type, int64_t*> node_time_;
  std::unordered_map<node_type, std::vector<int64_t>> num_sampled_nodes_per_hop_;
  std::unordered_map<rel_type, std::vector<int64_t>> num_sampled_edges_per_hop_;
  std::unordered_map<node_type, std::vector<int64_t>> sampled_batch_;
  std::unordered_map<node_type, std::vector<int64_t>> sampled_node_ids_;
  std::unordered_map<rel_type, std::vector<int64_t>> sampled_cols_;
  std::unordered_map<rel_type, std::vector<int64_t>> sampled_rows_;
};

PYBIND11_MODULE(relationallib, m) {
py::class_<relationallib::NeighborSampler>(m, "NeighborSampler")
.def(py::init<const std::vector<node_type>, std::vector<edge_type>, py::dict, py::dict, py::object, int>(),
  py::arg("node_types"),
  py::arg("edge_types"),
  py::arg("colptr"),
  py::arg("row"),
  py::arg("node_time"),
  py::arg("seed") = py::int_(123))
.def("seed", &relationallib::NeighborSampler::seed,
    py::arg("seed"))
.def("sample", &relationallib::NeighborSampler::sample,
    py::arg("num_neighbors"),
    py::arg("sampling_time_offsets"),
    py::arg("entity_table"),
    py::arg("seed_node"),
    py::arg("seed_time"));
}
}
